// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/roodox_core.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_ListDir_FullMethodName        = "/roodox.core.v1.CoreService/ListDir"
	CoreService_Stat_FullMethodName           = "/roodox.core.v1.CoreService/Stat"
	CoreService_ReadFile_FullMethodName       = "/roodox.core.v1.CoreService/ReadFile"
	CoreService_ReadFileRange_FullMethodName  = "/roodox.core.v1.CoreService/ReadFileRange"
	CoreService_WriteFileRange_FullMethodName = "/roodox.core.v1.CoreService/WriteFileRange"
	CoreService_SetFileSize_FullMethodName    = "/roodox.core.v1.CoreService/SetFileSize"
	CoreService_Delete_FullMethodName         = "/roodox.core.v1.CoreService/Delete"
	CoreService_Rename_FullMethodName         = "/roodox.core.v1.CoreService/Rename"
	CoreService_Mkdir_FullMethodName          = "/roodox.core.v1.CoreService/Mkdir"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Core file operations.
type CoreServiceClient interface {
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	ReadFileRange(ctx context.Context, in *ReadFileRangeRequest, opts ...grpc.CallOption) (*ReadFileRangeResponse, error)
	WriteFileRange(ctx context.Context, in *WriteFileRangeRequest, opts ...grpc.CallOption) (*WriteFileRangeResponse, error)
	SetFileSize(ctx context.Context, in *SetFileSizeRequest, opts ...grpc.CallOption) (*SetFileSizeResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, CoreService_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, CoreService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, CoreService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReadFileRange(ctx context.Context, in *ReadFileRangeRequest, opts ...grpc.CallOption) (*ReadFileRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileRangeResponse)
	err := c.cc.Invoke(ctx, CoreService_ReadFileRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) WriteFileRange(ctx context.Context, in *WriteFileRangeRequest, opts ...grpc.CallOption) (*WriteFileRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileRangeResponse)
	err := c.cc.Invoke(ctx, CoreService_WriteFileRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetFileSize(ctx context.Context, in *SetFileSizeRequest, opts ...grpc.CallOption) (*SetFileSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFileSizeResponse)
	err := c.cc.Invoke(ctx, CoreService_SetFileSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CoreService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, CoreService_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, CoreService_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// Core file operations.
type CoreServiceServer interface {
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ReadFileRange(context.Context, *ReadFileRangeRequest) (*ReadFileRangeResponse, error)
	WriteFileRange(context.Context, *WriteFileRangeRequest) (*WriteFileRangeResponse, error)
	SetFileSize(context.Context, *SetFileSizeRequest) (*SetFileSizeResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedCoreServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedCoreServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedCoreServiceServer) ReadFileRange(context.Context, *ReadFileRangeRequest) (*ReadFileRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFileRange not implemented")
}
func (UnimplementedCoreServiceServer) WriteFileRange(context.Context, *WriteFileRangeRequest) (*WriteFileRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFileRange not implemented")
}
func (UnimplementedCoreServiceServer) SetFileSize(context.Context, *SetFileSizeRequest) (*SetFileSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFileSize not implemented")
}
func (UnimplementedCoreServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCoreServiceServer) Rename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedCoreServiceServer) Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReadFileRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReadFileRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReadFileRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReadFileRange(ctx, req.(*ReadFileRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_WriteFileRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).WriteFileRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_WriteFileRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).WriteFileRange(ctx, req.(*WriteFileRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetFileSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFileSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetFileSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetFileSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetFileSize(ctx, req.(*SetFileSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDir",
			Handler:    _CoreService_ListDir_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _CoreService_Stat_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _CoreService_ReadFile_Handler,
		},
		{
			MethodName: "ReadFileRange",
			Handler:    _CoreService_ReadFileRange_Handler,
		},
		{
			MethodName: "WriteFileRange",
			Handler:    _CoreService_WriteFileRange_Handler,
		},
		{
			MethodName: "SetFileSize",
			Handler:    _CoreService_SetFileSize_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CoreService_Delete_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _CoreService_Rename_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _CoreService_Mkdir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	SyncService_GetFileMeta_FullMethodName      = "/roodox.core.v1.SyncService/GetFileMeta"
	SyncService_WriteFile_FullMethodName        = "/roodox.core.v1.SyncService/WriteFile"
	SyncService_WriteFileStream_FullMethodName  = "/roodox.core.v1.SyncService/WriteFileStream"
	SyncService_ListChangedFiles_FullMethodName = "/roodox.core.v1.SyncService/ListChangedFiles"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sync operations.
type SyncServiceClient interface {
	GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse], error)
	ListChangedFiles(ctx context.Context, in *ListChangedFilesRequest, opts ...grpc.CallOption) (*ListChangedFilesResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetaResponse)
	err := c.cc.Invoke(ctx, SyncService_GetFileMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SyncService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_WriteFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileChunk, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WriteFileStreamClient = grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse]

func (c *syncServiceClient) ListChangedFiles(ctx context.Context, in *ListChangedFilesRequest, opts ...grpc.CallOption) (*ListChangedFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangedFilesResponse)
	err := c.cc.Invoke(ctx, SyncService_ListChangedFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// Sync operations.
type SyncServiceServer interface {
	GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	WriteFileStream(grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]) error
	ListChangedFiles(context.Context, *ListChangedFilesRequest) (*ListChangedFilesResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMeta not implemented")
}
func (UnimplementedSyncServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSyncServiceServer) WriteFileStream(grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WriteFileStream not implemented")
}
func (UnimplementedSyncServiceServer) ListChangedFiles(context.Context, *ListChangedFilesRequest) (*ListChangedFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChangedFiles not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetFileMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_GetFileMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetFileMeta(ctx, req.(*GetFileMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_WriteFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).WriteFileStream(&grpc.GenericServerStream[WriteFileChunk, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_WriteFileStreamServer = grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]

func _SyncService_ListChangedFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangedFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).ListChangedFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_ListChangedFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).ListChangedFiles(ctx, req.(*ListChangedFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileMeta",
			Handler:    _SyncService_GetFileMeta_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SyncService_WriteFile_Handler,
		},
		{
			MethodName: "ListChangedFiles",
			Handler:    _SyncService_ListChangedFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteFileStream",
			Handler:       _SyncService_WriteFileStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/roodox_core.proto",
}

const (
	LockService_AcquireLock_FullMethodName = "/roodox.core.v1.LockService/AcquireLock"
	LockService_RenewLock_FullMethodName   = "/roodox.core.v1.LockService/RenewLock"
	LockService_ReleaseLock_FullMethodName = "/roodox.core.v1.LockService/ReleaseLock"
)

// LockServiceClient is the client API for LockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Lock operations.
type LockServiceClient interface {
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	RenewLock(ctx context.Context, in *RenewLockRequest, opts ...grpc.CallOption) (*RenewLockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
}

type lockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLockServiceClient(cc grpc.ClientConnInterface) LockServiceClient {
	return &lockServiceClient{cc}
}

func (c *lockServiceClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, LockService_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) RenewLock(ctx context.Context, in *RenewLockRequest, opts ...grpc.CallOption) (*RenewLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLockResponse)
	err := c.cc.Invoke(ctx, LockService_RenewLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, LockService_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockServiceServer is the server API for LockService service.
// All implementations must embed UnimplementedLockServiceServer
// for forward compatibility.
//
// Lock operations.
type LockServiceServer interface {
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	mustEmbedUnimplementedLockServiceServer()
}

// UnimplementedLockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockServiceServer struct{}

func (UnimplementedLockServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedLockServiceServer) RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLock not implemented")
}
func (UnimplementedLockServiceServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedLockServiceServer) mustEmbedUnimplementedLockServiceServer() {}
func (UnimplementedLockServiceServer) testEmbeddedByValue()                     {}

// UnsafeLockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockServiceServer will
// result in compilation errors.
type UnsafeLockServiceServer interface {
	mustEmbedUnimplementedLockServiceServer()
}

func RegisterLockServiceServer(s grpc.ServiceRegistrar, srv LockServiceServer) {
	// If the following call pancis, it indicates UnimplementedLockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockService_ServiceDesc, srv)
}

func _LockService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockService_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_RenewLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).RenewLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockService_RenewLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).RenewLock(ctx, req.(*RenewLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockService_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockService_ServiceDesc is the grpc.ServiceDesc for LockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.LockService",
	HandlerType: (*LockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireLock",
			Handler:    _LockService_AcquireLock_Handler,
		},
		{
			MethodName: "RenewLock",
			Handler:    _LockService_RenewLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _LockService_ReleaseLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	VersionService_GetHistory_FullMethodName = "/roodox.core.v1.VersionService/GetHistory"
	VersionService_GetVersion_FullMethodName = "/roodox.core.v1.VersionService/GetVersion"
)

// VersionServiceClient is the client API for VersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Version operations.
type VersionServiceClient interface {
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type versionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionServiceClient(cc grpc.ClientConnInterface) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, VersionService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, VersionService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServiceServer is the server API for VersionService service.
// All implementations must embed UnimplementedVersionServiceServer
// for forward compatibility.
//
// Version operations.
type VersionServiceServer interface {
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedVersionServiceServer()
}

// UnimplementedVersionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVersionServiceServer struct{}

func (UnimplementedVersionServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedVersionServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedVersionServiceServer) mustEmbedUnimplementedVersionServiceServer() {}
func (UnimplementedVersionServiceServer) testEmbeddedByValue()                        {}

// UnsafeVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionServiceServer will
// result in compilation errors.
type UnsafeVersionServiceServer interface {
	mustEmbedUnimplementedVersionServiceServer()
}

func RegisterVersionServiceServer(s grpc.ServiceRegistrar, srv VersionServiceServer) {
	// If the following call pancis, it indicates UnimplementedVersionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VersionService_ServiceDesc, srv)
}

func _VersionService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionService_ServiceDesc is the grpc.ServiceDesc for VersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _VersionService_GetHistory_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _VersionService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	AnalyzeService_AnalyzeBuildUnits_FullMethodName = "/roodox.core.v1.AnalyzeService/AnalyzeBuildUnits"
)

// AnalyzeServiceClient is the client API for AnalyzeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Build analysis.
type AnalyzeServiceClient interface {
	AnalyzeBuildUnits(ctx context.Context, in *AnalyzeBuildUnitsRequest, opts ...grpc.CallOption) (*AnalyzeBuildUnitsResponse, error)
}

type analyzeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzeServiceClient(cc grpc.ClientConnInterface) AnalyzeServiceClient {
	return &analyzeServiceClient{cc}
}

func (c *analyzeServiceClient) AnalyzeBuildUnits(ctx context.Context, in *AnalyzeBuildUnitsRequest, opts ...grpc.CallOption) (*AnalyzeBuildUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeBuildUnitsResponse)
	err := c.cc.Invoke(ctx, AnalyzeService_AnalyzeBuildUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzeServiceServer is the server API for AnalyzeService service.
// All implementations must embed UnimplementedAnalyzeServiceServer
// for forward compatibility.
//
// Build analysis.
type AnalyzeServiceServer interface {
	AnalyzeBuildUnits(context.Context, *AnalyzeBuildUnitsRequest) (*AnalyzeBuildUnitsResponse, error)
	mustEmbedUnimplementedAnalyzeServiceServer()
}

// UnimplementedAnalyzeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzeServiceServer struct{}

func (UnimplementedAnalyzeServiceServer) AnalyzeBuildUnits(context.Context, *AnalyzeBuildUnitsRequest) (*AnalyzeBuildUnitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeBuildUnits not implemented")
}
func (UnimplementedAnalyzeServiceServer) mustEmbedUnimplementedAnalyzeServiceServer() {}
func (UnimplementedAnalyzeServiceServer) testEmbeddedByValue()                        {}

// UnsafeAnalyzeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzeServiceServer will
// result in compilation errors.
type UnsafeAnalyzeServiceServer interface {
	mustEmbedUnimplementedAnalyzeServiceServer()
}

func RegisterAnalyzeServiceServer(s grpc.ServiceRegistrar, srv AnalyzeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyzeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzeService_ServiceDesc, srv)
}

func _AnalyzeService_AnalyzeBuildUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeBuildUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzeServiceServer).AnalyzeBuildUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzeService_AnalyzeBuildUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzeServiceServer).AnalyzeBuildUnits(ctx, req.(*AnalyzeBuildUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzeService_ServiceDesc is the grpc.ServiceDesc for AnalyzeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.AnalyzeService",
	HandlerType: (*AnalyzeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeBuildUnits",
			Handler:    _AnalyzeService_AnalyzeBuildUnits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	BuildService_StartBuild_FullMethodName      = "/roodox.core.v1.BuildService/StartBuild"
	BuildService_GetBuildStatus_FullMethodName  = "/roodox.core.v1.BuildService/GetBuildStatus"
	BuildService_FetchBuildLog_FullMethodName   = "/roodox.core.v1.BuildService/FetchBuildLog"
	BuildService_GetBuildProduct_FullMethodName = "/roodox.core.v1.BuildService/GetBuildProduct"
)

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Remote build.
type BuildServiceClient interface {
	StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error)
	GetBuildStatus(ctx context.Context, in *GetBuildStatusRequest, opts ...grpc.CallOption) (*GetBuildStatusResponse, error)
	FetchBuildLog(ctx context.Context, in *FetchBuildLogRequest, opts ...grpc.CallOption) (*FetchBuildLogResponse, error)
	GetBuildProduct(ctx context.Context, in *GetBuildProductRequest, opts ...grpc.CallOption) (*GetBuildProductResponse, error)
}

type buildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildServiceClient(cc grpc.ClientConnInterface) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildResponse)
	err := c.cc.Invoke(ctx, BuildService_StartBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetBuildStatus(ctx context.Context, in *GetBuildStatusRequest, opts ...grpc.CallOption) (*GetBuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildStatusResponse)
	err := c.cc.Invoke(ctx, BuildService_GetBuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) FetchBuildLog(ctx context.Context, in *FetchBuildLogRequest, opts ...grpc.CallOption) (*FetchBuildLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchBuildLogResponse)
	err := c.cc.Invoke(ctx, BuildService_FetchBuildLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetBuildProduct(ctx context.Context, in *GetBuildProductRequest, opts ...grpc.CallOption) (*GetBuildProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildProductResponse)
	err := c.cc.Invoke(ctx, BuildService_GetBuildProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
// All implementations must embed UnimplementedBuildServiceServer
// for forward compatibility.
//
// Remote build.
type BuildServiceServer interface {
	StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error)
	GetBuildStatus(context.Context, *GetBuildStatusRequest) (*GetBuildStatusResponse, error)
	FetchBuildLog(context.Context, *FetchBuildLogRequest) (*FetchBuildLogResponse, error)
	GetBuildProduct(context.Context, *GetBuildProductRequest) (*GetBuildProductResponse, error)
	mustEmbedUnimplementedBuildServiceServer()
}

// UnimplementedBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildServiceServer struct{}

func (UnimplementedBuildServiceServer) StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBuild not implemented")
}
func (UnimplementedBuildServiceServer) GetBuildStatus(context.Context, *GetBuildStatusRequest) (*GetBuildStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuildStatus not implemented")
}
func (UnimplementedBuildServiceServer) FetchBuildLog(context.Context, *FetchBuildLogRequest) (*FetchBuildLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBuildLog not implemented")
}
func (UnimplementedBuildServiceServer) GetBuildProduct(context.Context, *GetBuildProductRequest) (*GetBuildProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuildProduct not implemented")
}
func (UnimplementedBuildServiceServer) mustEmbedUnimplementedBuildServiceServer() {}
func (UnimplementedBuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildServiceServer will
// result in compilation errors.
type UnsafeBuildServiceServer interface {
	mustEmbedUnimplementedBuildServiceServer()
}

func RegisterBuildServiceServer(s grpc.ServiceRegistrar, srv BuildServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildService_ServiceDesc, srv)
}

func _BuildService_StartBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).StartBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_StartBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).StartBuild(ctx, req.(*StartBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_GetBuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetBuildStatus(ctx, req.(*GetBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_FetchBuildLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBuildLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).FetchBuildLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_FetchBuildLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).FetchBuildLog(ctx, req.(*FetchBuildLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetBuildProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetBuildProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_GetBuildProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetBuildProduct(ctx, req.(*GetBuildProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildService_ServiceDesc is the grpc.ServiceDesc for BuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBuild",
			Handler:    _BuildService_StartBuild_Handler,
		},
		{
			MethodName: "GetBuildStatus",
			Handler:    _BuildService_GetBuildStatus_Handler,
		},
		{
			MethodName: "FetchBuildLog",
			Handler:    _BuildService_FetchBuildLog_Handler,
		},
		{
			MethodName: "GetBuildProduct",
			Handler:    _BuildService_GetBuildProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	ControlPlaneService_RegisterDevice_FullMethodName    = "/roodox.core.v1.ControlPlaneService/RegisterDevice"
	ControlPlaneService_Heartbeat_FullMethodName         = "/roodox.core.v1.ControlPlaneService/Heartbeat"
	ControlPlaneService_GetAssignedConfig_FullMethodName = "/roodox.core.v1.ControlPlaneService/GetAssignedConfig"
	ControlPlaneService_ReportSyncState_FullMethodName   = "/roodox.core.v1.ControlPlaneService/ReportSyncState"
	ControlPlaneService_ReportMountState_FullMethodName  = "/roodox.core.v1.ControlPlaneService/ReportMountState"
	ControlPlaneService_UploadDiagnostics_FullMethodName = "/roodox.core.v1.ControlPlaneService/UploadDiagnostics"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client control-plane API.
type ControlPlaneServiceClient interface {
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetAssignedConfig(ctx context.Context, in *GetAssignedConfigRequest, opts ...grpc.CallOption) (*GetAssignedConfigResponse, error)
	ReportSyncState(ctx context.Context, in *ReportSyncStateRequest, opts ...grpc.CallOption) (*ReportSyncStateResponse, error)
	ReportMountState(ctx context.Context, in *ReportMountStateRequest, opts ...grpc.CallOption) (*ReportMountStateResponse, error)
	UploadDiagnostics(ctx context.Context, in *UploadDiagnosticsRequest, opts ...grpc.CallOption) (*UploadDiagnosticsResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetAssignedConfig(ctx context.Context, in *GetAssignedConfigRequest, opts ...grpc.CallOption) (*GetAssignedConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssignedConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetAssignedConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportSyncState(ctx context.Context, in *ReportSyncStateRequest, opts ...grpc.CallOption) (*ReportSyncStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSyncStateResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReportSyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportMountState(ctx context.Context, in *ReportMountStateRequest, opts ...grpc.CallOption) (*ReportMountStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMountStateResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReportMountState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UploadDiagnostics(ctx context.Context, in *UploadDiagnosticsRequest, opts ...grpc.CallOption) (*UploadDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDiagnosticsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UploadDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// Client control-plane API.
type ControlPlaneServiceServer interface {
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetAssignedConfig(context.Context, *GetAssignedConfigRequest) (*GetAssignedConfigResponse, error)
	ReportSyncState(context.Context, *ReportSyncStateRequest) (*ReportSyncStateResponse, error)
	ReportMountState(context.Context, *ReportMountStateRequest) (*ReportMountStateResponse, error)
	UploadDiagnostics(context.Context, *UploadDiagnosticsRequest) (*UploadDiagnosticsResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedControlPlaneServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetAssignedConfig(context.Context, *GetAssignedConfigRequest) (*GetAssignedConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignedConfig not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportSyncState(context.Context, *ReportSyncStateRequest) (*ReportSyncStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSyncState not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportMountState(context.Context, *ReportMountStateRequest) (*ReportMountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMountState not implemented")
}
func (UnimplementedControlPlaneServiceServer) UploadDiagnostics(context.Context, *UploadDiagnosticsRequest) (*UploadDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDiagnostics not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetAssignedConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignedConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetAssignedConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetAssignedConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetAssignedConfig(ctx, req.(*GetAssignedConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportSyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSyncStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReportSyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReportSyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReportSyncState(ctx, req.(*ReportSyncStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportMountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReportMountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReportMountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReportMountState(ctx, req.(*ReportMountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UploadDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UploadDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UploadDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UploadDiagnostics(ctx, req.(*UploadDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _ControlPlaneService_RegisterDevice_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlaneService_Heartbeat_Handler,
		},
		{
			MethodName: "GetAssignedConfig",
			Handler:    _ControlPlaneService_GetAssignedConfig_Handler,
		},
		{
			MethodName: "ReportSyncState",
			Handler:    _ControlPlaneService_ReportSyncState_Handler,
		},
		{
			MethodName: "ReportMountState",
			Handler:    _ControlPlaneService_ReportMountState_Handler,
		},
		{
			MethodName: "UploadDiagnostics",
			Handler:    _ControlPlaneService_UploadDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}

const (
	AdminConsoleService_ListDevices_FullMethodName            = "/roodox.core.v1.AdminConsoleService/ListDevices"
	AdminConsoleService_GetDeviceDetail_FullMethodName        = "/roodox.core.v1.AdminConsoleService/GetDeviceDetail"
	AdminConsoleService_IssueJoinBundle_FullMethodName        = "/roodox.core.v1.AdminConsoleService/IssueJoinBundle"
	AdminConsoleService_UpdateDevicePolicy_FullMethodName     = "/roodox.core.v1.AdminConsoleService/UpdateDevicePolicy"
	AdminConsoleService_RequestClientAction_FullMethodName    = "/roodox.core.v1.AdminConsoleService/RequestClientAction"
	AdminConsoleService_GetServerRuntime_FullMethodName       = "/roodox.core.v1.AdminConsoleService/GetServerRuntime"
	AdminConsoleService_GetServerObservability_FullMethodName = "/roodox.core.v1.AdminConsoleService/GetServerObservability"
	AdminConsoleService_TriggerServerBackup_FullMethodName    = "/roodox.core.v1.AdminConsoleService/TriggerServerBackup"
	AdminConsoleService_ShutdownServer_FullMethodName         = "/roodox.core.v1.AdminConsoleService/ShutdownServer"
)

// AdminConsoleServiceClient is the client API for AdminConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin console query API.
type AdminConsoleServiceClient interface {
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	GetDeviceDetail(ctx context.Context, in *GetDeviceDetailRequest, opts ...grpc.CallOption) (*GetDeviceDetailResponse, error)
	IssueJoinBundle(ctx context.Context, in *IssueJoinBundleRequest, opts ...grpc.CallOption) (*IssueJoinBundleResponse, error)
	UpdateDevicePolicy(ctx context.Context, in *UpdateDevicePolicyRequest, opts ...grpc.CallOption) (*UpdateDevicePolicyResponse, error)
	RequestClientAction(ctx context.Context, in *RequestClientActionRequest, opts ...grpc.CallOption) (*RequestClientActionResponse, error)
	GetServerRuntime(ctx context.Context, in *GetServerRuntimeRequest, opts ...grpc.CallOption) (*GetServerRuntimeResponse, error)
	GetServerObservability(ctx context.Context, in *GetServerObservabilityRequest, opts ...grpc.CallOption) (*GetServerObservabilityResponse, error)
	TriggerServerBackup(ctx context.Context, in *TriggerServerBackupRequest, opts ...grpc.CallOption) (*TriggerServerBackupResponse, error)
	ShutdownServer(ctx context.Context, in *ShutdownServerRequest, opts ...grpc.CallOption) (*ShutdownServerResponse, error)
}

type adminConsoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminConsoleServiceClient(cc grpc.ClientConnInterface) AdminConsoleServiceClient {
	return &adminConsoleServiceClient{cc}
}

func (c *adminConsoleServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) GetDeviceDetail(ctx context.Context, in *GetDeviceDetailRequest, opts ...grpc.CallOption) (*GetDeviceDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceDetailResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_GetDeviceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) IssueJoinBundle(ctx context.Context, in *IssueJoinBundleRequest, opts ...grpc.CallOption) (*IssueJoinBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueJoinBundleResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_IssueJoinBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) UpdateDevicePolicy(ctx context.Context, in *UpdateDevicePolicyRequest, opts ...grpc.CallOption) (*UpdateDevicePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDevicePolicyResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_UpdateDevicePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) RequestClientAction(ctx context.Context, in *RequestClientActionRequest, opts ...grpc.CallOption) (*RequestClientActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestClientActionResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_RequestClientAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) GetServerRuntime(ctx context.Context, in *GetServerRuntimeRequest, opts ...grpc.CallOption) (*GetServerRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerRuntimeResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_GetServerRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) GetServerObservability(ctx context.Context, in *GetServerObservabilityRequest, opts ...grpc.CallOption) (*GetServerObservabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerObservabilityResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_GetServerObservability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) TriggerServerBackup(ctx context.Context, in *TriggerServerBackupRequest, opts ...grpc.CallOption) (*TriggerServerBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerServerBackupResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_TriggerServerBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConsoleServiceClient) ShutdownServer(ctx context.Context, in *ShutdownServerRequest, opts ...grpc.CallOption) (*ShutdownServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownServerResponse)
	err := c.cc.Invoke(ctx, AdminConsoleService_ShutdownServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminConsoleServiceServer is the server API for AdminConsoleService service.
// All implementations must embed UnimplementedAdminConsoleServiceServer
// for forward compatibility.
//
// Admin console query API.
type AdminConsoleServiceServer interface {
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	GetDeviceDetail(context.Context, *GetDeviceDetailRequest) (*GetDeviceDetailResponse, error)
	IssueJoinBundle(context.Context, *IssueJoinBundleRequest) (*IssueJoinBundleResponse, error)
	UpdateDevicePolicy(context.Context, *UpdateDevicePolicyRequest) (*UpdateDevicePolicyResponse, error)
	RequestClientAction(context.Context, *RequestClientActionRequest) (*RequestClientActionResponse, error)
	GetServerRuntime(context.Context, *GetServerRuntimeRequest) (*GetServerRuntimeResponse, error)
	GetServerObservability(context.Context, *GetServerObservabilityRequest) (*GetServerObservabilityResponse, error)
	TriggerServerBackup(context.Context, *TriggerServerBackupRequest) (*TriggerServerBackupResponse, error)
	ShutdownServer(context.Context, *ShutdownServerRequest) (*ShutdownServerResponse, error)
	mustEmbedUnimplementedAdminConsoleServiceServer()
}

// UnimplementedAdminConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminConsoleServiceServer struct{}

func (UnimplementedAdminConsoleServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedAdminConsoleServiceServer) GetDeviceDetail(context.Context, *GetDeviceDetailRequest) (*GetDeviceDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceDetail not implemented")
}
func (UnimplementedAdminConsoleServiceServer) IssueJoinBundle(context.Context, *IssueJoinBundleRequest) (*IssueJoinBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueJoinBundle not implemented")
}
func (UnimplementedAdminConsoleServiceServer) UpdateDevicePolicy(context.Context, *UpdateDevicePolicyRequest) (*UpdateDevicePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevicePolicy not implemented")
}
func (UnimplementedAdminConsoleServiceServer) RequestClientAction(context.Context, *RequestClientActionRequest) (*RequestClientActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestClientAction not implemented")
}
func (UnimplementedAdminConsoleServiceServer) GetServerRuntime(context.Context, *GetServerRuntimeRequest) (*GetServerRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerRuntime not implemented")
}
func (UnimplementedAdminConsoleServiceServer) GetServerObservability(context.Context, *GetServerObservabilityRequest) (*GetServerObservabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerObservability not implemented")
}
func (UnimplementedAdminConsoleServiceServer) TriggerServerBackup(context.Context, *TriggerServerBackupRequest) (*TriggerServerBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerServerBackup not implemented")
}
func (UnimplementedAdminConsoleServiceServer) ShutdownServer(context.Context, *ShutdownServerRequest) (*ShutdownServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownServer not implemented")
}
func (UnimplementedAdminConsoleServiceServer) mustEmbedUnimplementedAdminConsoleServiceServer() {}
func (UnimplementedAdminConsoleServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminConsoleServiceServer will
// result in compilation errors.
type UnsafeAdminConsoleServiceServer interface {
	mustEmbedUnimplementedAdminConsoleServiceServer()
}

func RegisterAdminConsoleServiceServer(s grpc.ServiceRegistrar, srv AdminConsoleServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminConsoleService_ServiceDesc, srv)
}

func _AdminConsoleService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_GetDeviceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).GetDeviceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_GetDeviceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).GetDeviceDetail(ctx, req.(*GetDeviceDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_IssueJoinBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueJoinBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).IssueJoinBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_IssueJoinBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).IssueJoinBundle(ctx, req.(*IssueJoinBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_UpdateDevicePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDevicePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).UpdateDevicePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_UpdateDevicePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).UpdateDevicePolicy(ctx, req.(*UpdateDevicePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_RequestClientAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClientActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).RequestClientAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_RequestClientAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).RequestClientAction(ctx, req.(*RequestClientActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_GetServerRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).GetServerRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_GetServerRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).GetServerRuntime(ctx, req.(*GetServerRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_GetServerObservability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerObservabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).GetServerObservability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_GetServerObservability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).GetServerObservability(ctx, req.(*GetServerObservabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_TriggerServerBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerServerBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).TriggerServerBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_TriggerServerBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).TriggerServerBackup(ctx, req.(*TriggerServerBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConsoleService_ShutdownServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConsoleServiceServer).ShutdownServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConsoleService_ShutdownServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConsoleServiceServer).ShutdownServer(ctx, req.(*ShutdownServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminConsoleService_ServiceDesc is the grpc.ServiceDesc for AdminConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roodox.core.v1.AdminConsoleService",
	HandlerType: (*AdminConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _AdminConsoleService_ListDevices_Handler,
		},
		{
			MethodName: "GetDeviceDetail",
			Handler:    _AdminConsoleService_GetDeviceDetail_Handler,
		},
		{
			MethodName: "IssueJoinBundle",
			Handler:    _AdminConsoleService_IssueJoinBundle_Handler,
		},
		{
			MethodName: "UpdateDevicePolicy",
			Handler:    _AdminConsoleService_UpdateDevicePolicy_Handler,
		},
		{
			MethodName: "RequestClientAction",
			Handler:    _AdminConsoleService_RequestClientAction_Handler,
		},
		{
			MethodName: "GetServerRuntime",
			Handler:    _AdminConsoleService_GetServerRuntime_Handler,
		},
		{
			MethodName: "GetServerObservability",
			Handler:    _AdminConsoleService_GetServerObservability_Handler,
		},
		{
			MethodName: "TriggerServerBackup",
			Handler:    _AdminConsoleService_TriggerServerBackup_Handler,
		},
		{
			MethodName: "ShutdownServer",
			Handler:    _AdminConsoleService_ShutdownServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/roodox_core.proto",
}
